In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [2]:
import pandas as pd
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['target'] = iris.target


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['target'],axis='columns'),iris.target,test_size=0.2)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(['target'],axis='columns'),iris.target,test_size=0.2)

In [12]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
model = RandomForestClassifier(n_estimators=40)
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.9666666666666667

In [14]:
y_predicted = model.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predicted)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]])

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [24]:

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [29]:

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test, y_test)

0.9685185185185186

In [30]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in folds.split(digits.data,digits.target):
  X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], \
   digits.target[train_index], digits.target[test_index]
   scores_logistic.append(get_score())

  




In [37]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [31]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [32]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [33]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [34]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train,y_train)
  model.score(X_test,y_test)

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [40]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)


0.879258224705152

In [43]:
scores12 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)

In [44]:
scores12

array([0.89444444, 0.97777778, 0.92777778, 0.92777778, 0.97222222,
       0.96666667, 0.97222222, 0.97206704, 0.89944134, 0.93296089])

In [45]:
np.average(scores12)

0.9443358162631906

In [46]:
np.argmax(scores12)

1

In [47]:
iris = load_iris()

In [48]:
score =  cross_val_score(LogisticRegression(),iris.data,iris.target)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [49]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [53]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(iris.data)

In [54]:
l_scores = cross_val_score(LogisticRegression(), scaler, iris.target)

TypeError: ignored

In [55]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

NameError: ignored