In [34]:
%tensorflow_version 2.x
import tensorflow as tf  # now import the tensorflow module
print(tf.version) 

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [35]:
string = tf.Variable('this is my string',tf.string)

In [36]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is my string'>

In [37]:
with tf.Session() as sess:  
  print(string) 

AttributeError: ignored

In [38]:
tf.compat.v1.Session()
print(string.value)

<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is my string'>>


In [39]:
tf.print(string)

this is my string


In [40]:
matrix1 = tf.constant([[3., 3.],[5.,7.]])
matrix2 = tf.constant([[6.,8.]])

In [41]:
print(tf.matmul(matrix1,matrix2))

InvalidArgumentError: ignored

In [42]:
product = tf.matmul(matrix1, matrix2)

InvalidArgumentError: ignored

In [43]:
import tensorflow as tf

A1 = tf.constant([[2, 24], [2, 26], [2, 57]])
B1 = tf.constant([[1000], [150]])
C1 = tf.matmul(A1, B1)


In [44]:
tf.print(C1)

[[5600]
 [5900]
 [10550]]


In [20]:
import numpy as np
 
#create numpy_array
numpy_array = np.array([[1,2],[3,4]])
 
# convert it to tensorflow
tensor1 = tf.convert_to_tensor(numpy_array)
print(tensor1)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [21]:
numpy_data = np.array([[[1,3,4],[5,6,7],[8,9,0]]])

In [22]:
tensor2 = tf.convert_to_tensor(numpy_data)
print(tensor2)

tf.Tensor(
[[[1 3 4]
  [5 6 7]
  [8 9 0]]], shape=(1, 3, 3), dtype=int64)


In [23]:
number = tf.Variable(324, tf.int16)

In [24]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>

In [25]:
number2 = tf.Variable(23.0,tf.float64)

In [26]:
tf.print(number2)

23


In [32]:
rank2_tensor = tf.Variable([[["a","b"],["c","d"],["k","d"]]],tf.string)

In [33]:
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1, 3, 2) dtype=string, numpy=
array([[[b'a', b'b'],
        [b'c', b'd'],
        [b'k', b'd']]], dtype=object)>


In [48]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])

In [49]:
print(tensor1)
print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [50]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [51]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [54]:
columns = tensor[:,0]

In [55]:
columns

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  6, 11, 16], dtype=int32)>